version: "3"

services:
  funkreview-db:
    image: postgres:16.0
    container_name: funkreview-db
    environment:
      - POSTGRES_USER=${FUNKREVIEW_DB_USER}
      - POSTGRES_DB=${FUNKREVIEW_DB_NAME}
      - POSTGRES_PASSWORD=${FUNKREVIEW_DB_PASSWORD}
      - POSTGRES_PORT=${FUNKREVIEW_DB_PORT}
    volumes:
      - ./funkreview-db/data:/var/lib/postgresql/data
      - ./funkreview-db/seed:/docker-entrypoint-initdb.d/
    ports:
      - ${FUNKREVIEW_DB_PORT}:${FUNKREVIEW_DB_PORT}

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9.1
    container_name: zookeeper
    ports:
      - ${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.6.0
    container_name: kafka
    ports:
      - 29092:29092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:${ZOOKEEPER_PORT}
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:${KAFKA_PORT},OUTSIDE://:29092
      - KAFKA_CFG_LISTENERS=INSIDE://:${KAFKA_PORT},OUTSIDE://:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INSIDE
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  datagen:
    build: ./datagen
    container_name: datagen
    env_file:
      - .env
    volumes:
      - ./datagen/src:/src
    depends_on:
      - kafka

  jobmanager:
    build: ./flink
    container_name: jobmanager
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./flink/src:/opt/flink/src
    command: jobmanager
    depends_on:
      - kafka

  taskmanager:
    build: ./flink
    container_name: taskmanager
    scale: 1
    env_file:
      - .env
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - ./flink/src:/opt/flink/src
    command: taskmanager
    depends_on:
      - jobmanager
